export default {
  title: "Visione",
  
  p1:"Phad è una azienda fondata nel 2017 da due ingegneri specializzati nelle telecomunicazioni con oltre 20 anni di esperienza lavorativa presso aziende multinazionali operanti nel campo della fornitura di servizi professionali per operatori di telecomunicazioni mobile nazionali ed internazionali e per industrie all’avanguardia.",

  p2:"Sin dall’inizio della propria attività imprenditoriale la Phad si è impegnata a servire servizi professionali di alto contenuto tecnologico e con forti potenzialità di crescita per tutti quei clienti stimolati da tali iniziative.",

  p3: "All’inizio del 2022 Phad ha sentito l’esigenza di espandersi a proporre servizi ICT alle imprese impegnate nei mercati dove sono richieste competenze nell’integrazione di sistemi e conoscenze di ambiti specifici per supportare i General Contractor EPC.",

  p4:"Questo è stato possibile inserendo in azienda figure professionali di maturata esperienza di contract e project management e nello stesso tempo significativa esperienza nella implementazione di progetti di ingegneria con sistemi complessi su scala medio-grande per organizzazioni multinazionali.",

  p5: "Per alcuni progetti, dove viene espressamento richiesto dal cliente, Phad mette a disposizione le prorie conoscenze e risorse seguendo un approccio a task e/o a staff augmentation per alleviare il carico di lavoro che deve espletare il cliente per il prorio business oppure per progetti verso terze parti.",

  p6: "Al fine di poter servire il cliente in un approccio olistico Phad ha una rete di partner con provata esperienza nel proprio specifico ambito di business dove poter attingere risorse specializzate che consentono alla Phad di essere il referente unico di progetto per il cliente che così si concentra sulla gestione del programma e controllo dei deliverables del proprio fornitore. Le risorse specializzate messe a disposizione del cliente sono sempre disponibili a viaggiare per effettuare attività in sito (onshore) oltre che ad effettuare le normali mansioni di servizi professionali dalle sedi del cliente a cui afferiscono i progetti di pertinenza.",
  p6l1: "RF Wireless design engineer",
  p6l2: "TLC Network design engineer",
  p6l3: "Certain system design engineers",
  p6l4: "OSS network management INMS and asset management MMIS",
  p6l5: "Scada platform",
  p6l6: "Protocol adapter software developers",
  p6l7: "Project accountant",
  p6l8: "Sub-contract administrator",
  p7: "Le risorse di Phad si occupano di verificare le specifiche tecniche, ridigere il progetto esecutivo che copre i requisiti di capitolato, sviluppare la documentazione ingegneristica, implementare eventuali moduli software di interfacciamento, configurare e testare gli apparati ITC in campo.",

  subTitle: "Visione",

  sP1: "L’attuale contesto industriale non consente a nessuna azienda di servizi di fornire soluzioni verticali per lo specifico ambito di business senza tenere conto degli aspetti di immediato ritorno dell’investimento, robustezza della soluzione implementata, facilità di utilizzo da parte degli utenti, bassi costi di evolutive e manutenzione, l’impatto ambientale e apertura naturale nell’interfacciamento con altri moduli SW e/o piattaforme di business che richiedono la condivisione di informazioni e dati.",

  sP2: "La trasformazione digitale sta contribuendo in maniera efficace a rivedere processi e tools utilizzati dalle aziende in modo da rendere più fluida la condivisione delle performance, la velocità nel avere dati verificati a supporto del business, riduzione dei tempi di attraversamento per reperire le vari fonti di informazioni grazie alla convergenza delle tecnologie di informazione e operazionali IT/OT. Uno dei mercati che sarà maggiormente impattato dalla spinta digitale è il mercato ferroviario fortemente regolamentato e chiuso in maniera preventiva all’innovazione tecnologica per principi di sicurezza ed affidabilità. La trasformazione digitale della supply chain e l’attenzione degli azionisti nella sostenibilità economica ed ambientale dei sistemi complessi adottati dall’operatore di infrastrutture di rete nel gestire il trasporto pubblico comporterà la rivisitazione delle procedure e soluzioni tecniche adottate fino ad oggi per renderle sicure a 360° senza dover rinunciare al beneficio delle nuove tecnologie.",

  sP3: "C’è un percorso chiaro da seguire, utilizzando le nuove tecnologie e realizzando un approccio olistico integrato senza compromettere l’affidabilità delle infrastrutture ferroviarie ma allo stesso tempo ridurre il numero di incidenti che causano danni e problemi di sicurezza.",

  sP5: "Per le aziende che operano nel fornire soluzioni nel settore dei sistemi ferroviari, veicoli e segnalamento, questo viaggio di trasformazione digitale ITC è iniziato già da alcuni anni e grazie ai fondi del PNRR ci si augura che presto sia gli operatori del trasporto pubblico che i viaggitari possano benificiare di questa trasformazione.",

  sP6: "In molti altri settori dell’industrie la trasformazione digitale e la convergenza IT/OT è stata una scelta obligata per poter essere competitivi. La vera sfida è stata nel coraggio di rivedere i processo aziendali che si portano dietro le persone che hanno fatto la storia delle varie aziende a cui appartengono e superare così i problemi culturali di governance ed autoreferenzialità, sempre difficile da prendere nel verso giusto. Con un numero così grande di stakeholders nelle industrie, con diverse motivazioni, culture, obiettivi di competizione, il primo passo è quello di identificare il ruolo di ognuno all’interno delle organizzazioni, e motivare l’individuo a prendersi le responsabilità che il proprio ruolo necessita senza sentirsi soffocato da processi complessi da gestire. Per far ciò occorre avere risorse in grado di creare dei team multidisciplinari che hanno in comune obiettivi e motivazioni di crescita sostenibile, e trovare un linguaggio comune tra questi diversi enti che compongono la struttura organizzativa delle aziende. Oltretutto, anche far collaborare diverse funzioni della stessa azienda è un punto critico che la trasformazione digitale non può confinare nelle utilizzo degli stessi sistemi informativi. Per far sì che questi siano stimolati alla collaborazione e quindi alla crescita della azienda è importante focalizzarsi sulle differenze e rispettare le preoccupazioni di entrambi gli individui che vedono da punti di vista differenti le iniziative. Ad esempio, la sicurezza IT crede che verrà impattata molto pesantemente dalle necessità del reparto OT, che considerano “il wild west della sicurezza”, mentre l’OT ritiene che i team di sicurezza IT fermeranno e/o rallenteranno le loro implementazioni/operazioni, causando disservizi sul business, mancare il rispetto dei tempi di delivery e poco agiltà nel ripristino della operatività. Pertanto, ad esempio la convergenza IT/OT deve essere un’iniziativa di business di una azienda, piuttosto che una iniziativa dettata dai singoli enti tecnici.",
}