function Top() {
  return (
    <section>
      <h1>WE TRANSFORM TODAY‘S AMBITIOUS IDEAS INTO  TOMORROW’S SOLUTIONS</h1>
      
      <h2>PHAD SUPPORTS THE CUSTOMERS DELIVERY TEAM WITH FULL TIME EQUIVALENT MANAGERS, ENGINEERS, AND TECHNICIANS FOR THE ENTIRE DURATION OF THE PROJECT</h2>

      <button>LEARN MORE</button>
    </section>
  );
}

export default Top;